services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: sanasana-laravel
    volumes:
      - ./src:/var/www/html # Montar el código en el contenedor, sobreescribe el COPY del Dockerfile
    ports:
      - "80:80"  # Exponer el puerto 80
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: sanasana-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
