services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: sanasana-laravel
    #volumes:
    #  - ./src:/var/www/html # Montar el código en el contenedor, sobreescribe el COPY del Dockerfile
    #command: "php artisan serve --host 0.0.0.0"
    ports:
      - "8000:8000"
    user: www-data
    command: bash -c "composer install && php artisan serve --host 0.0.0.0"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: sanasana-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
